### ISSUE TITLE
Show Disqus comments by default

### ISSUE THREAD

**Issue by etem** [gayanvirajith/gaya#10]
Is it possible to configure comments to show by default?
To see comments now user needs to click "View comments" link at the bottom of post page.

**Comment by gayanvirajith** [comment]
Hi Etem,

May be this would help you. Please try add following javascript. 

```
/*
 * Show disqus comments
 */
jQuery(document).ready(function() {
    initDisqusComments();
});
```

**Comment by etem** [comment]
Thank you,but the code doesn't works.

**Comment by gayanvirajith** [comment]
Sorry Etem,

Here are the steps.
1. In `_layouts/default.html` modify the `gaya.min.js` javascript import to `gaya.js`.
2. In `assets/js/gaya.js` comment out the line 127, 129 and 130 as follows:

```
  // $('.load-view').click(function(){
    initDisqusComments();
    // $(this).fadeOut(200);
  // });
```
1. Finally you can remove `View comments` anchor tag from `_layouts/post.html' 

Thanks

**Comment by etem** [comment]
It works perfectly.
Thank you so much :)
