### ISSUE TITLE
github syntax highlighting

### ISSUE THREAD

**Issue by ghost** [gayanvirajith/gaya#11]
It can not support syntax highlighting like

``````
//```objc
//- (void)aFunction{}
//```
``````

I don't know why, Please help me.
Here is my blog link http://arlenkou.com/ios/2015/03/27/Hidden-Tabbar-when-ViewController-is-Pushed/

**Comment by ghost** [comment]
I have resolved it by myself. Thank you.

**Comment by ArlenKou** [comment]
I have resolved it by myself. Thank you.

**Comment by gayanvirajith** [comment]
Glad you solved it. Thanks
