### ISSUE TITLE
The author avatar showed is not the provided in the configuration file

### ISSUE THREAD

**Issue by josejuansanchez** [gayanvirajith/gaya#4]
The author avatar is hardcoded as '/assets/images/avatar.jpg'  in the file: _includes/author.html, and it should use the value provided by: site.author_thumbnail in _config.yml

**Comment by gayanvirajith** [comment]
@josejuansanchez :+1:  Thank you so much.

**Comment by josejuansanchez** [comment]
@gayanvirajith Thank you to you for sharing the source code of this project! :)
